/*9. Título do livro, nome da editora que o publicou e a descrição do assunto*/

CREATE TABLE EDITORA (
    COD_ED SERIAL PRIMARY KEY, 
    NOME VARCHAR(100), 
    LOCALIZACAO VARCHAR(100)
);

INSERT INTO EDITORA (NOME, LOCALIZACAO)
VALUES ('A', 'RUA DO MEDO');
INSERT INTO EDITORA (NOME, LOCALIZACAO)
VALUES ('B', 'BECO DIAGONAL');
INSERT INTO EDITORA (NOME, LOCALIZACAO)
VALUES ('C', 'RUA DO APAVORO');

CREATE TABLE LIVRO (
    COD_LIV SERIAL PRIMARY KEY, 
    COD_ED INT, NOME VARCHAR(100), 
    DESCRICAO VARCHAR(300), 
    FOREIGN KEY (COD_ED) REFERENCES EDITORA(COD_ED)
);

INSERT INTO LIVRO (COD_ED, NOME, DESCRICAO)
VALUES (1, 'RARI POTER', 'BRIGA DE BRUXOS');
INSERT INTO LIVRO (COD_ED, NOME, DESCRICAO)
VALUES (2, 'SENHOR DOS ANEIS', 'UM SENHOR QUE FAZIA ANEIS');
INSERT INTO LIVRO (COD_ED, NOME, DESCRICAO)
VALUES (3, 'PERCY JACKSON', 'PRIMO DO MAICON JACKSON');

SELECT L.NOME, E.NOME, L.DESCRICAO FROM EDITORA AS E 
JOIN LIVRO AS L ON E.COD_ED = L.COD_ED;