/*18. O nome das categorias que foram reservadas pela Maria ou que foram ocupadas pelo João 
quando ele foi atendido pelo Joaquim. */

/*CATEGOORIA*/
CREATE TABLE CATEGORIA (
    COD_CAT SERIAL PRIMARY KEY, 
    NOME VARCHAR(100), 
    PRECO INT, 
    DESCRICAO TEXT
);
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('SUPER LUXO', 300, 'PARA MUITO RICOS');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('LUXO', 200, 'PARA RICOS');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('MEDIO', 150, 'CLASSE MEDIA');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('BASICA', 100, 'PARA POBRES');

/*APARTAMENTO*/
CREATE TABLE APARTAMENTO (NUM_AP SERIAL PRIMARY KEY, 
    COD_CAT INT,
    FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA(COD_CAT)
);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (1);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (2);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (3);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (4);

/*HOSPEDAGEM*/
CREATE TABLE HOSPEDAGEM (
    COD_HOSPEDAGEM SERIAL PRIMARY KEY, 
    NUM_AP INT, 
    COD_HOSP INT, 
    COD_FUNC INT, 
    DT_ENT DATE, 
    DT_SAIDA DATE,
    FOREIGN KEY (NUM_AP) REFERENCES APARTAMENTO(NUM_AP),
    FOREIGN KEY (COD_HOSP) REFERENCES HOSPEDE(COD_HOSP),
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC)
);
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (1, 1, 1, '2025-1-1', '2025-1-2');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (2, 2, 2, '2025-1-1', '2025-1-3');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (3, 3, 3, '2025-1-1', '2025-1-4');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, COD_FUNC, DT_ENT, DT_SAIDA)
VALUES (4, 4, 4, '2025-1-1', NULL);

/*RESERVA*/
CREATE TABLE RESERVA (
    COD_RESERVA SERIAL PRIMARY KEY,
    NUM_AP INT,
    COD_HOSP INT,
    COD_FUNC INT,
    DT_RESERVA DATE,
    FOREIGN KEY (NUM_AP) REFERENCES APARTAMENTO(NUM_AP),
    FOREIGN KEY (COD_HOSP) REFERENCES HOSPEDE(COD_HOSP),
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC)
)
INSERT INTO RESERVA (NUM_AP, COD_HOSP, COD_FUNC, DT_RESERVA)
VALUES (2, 2, 2, '2025-01-10'); 
INSERT INTO RESERVA (NUM_AP, COD_HOSP, COD_FUNC, DT_RESERVA)
VALUES (1, 3, 1, '2025-01-11'); 
INSERT INTO RESERVA (NUM_AP, COD_HOSP, COD_FUNC, DT_RESERVA)
VALUES (2, 4, 3, '2025-01-12'); 

/*HOSPPEDE*/
CREATE TABLE HOSPEDE (
    COD_HOSP SERIAL PRIMARY KEY, 
    NOME VARCHAR(100), 
    DT_NASC DATE
);
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('CHICO', '2005-1-6');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('JOAO', '1967-3-20');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('DONA ANGELA', '1972-12-8');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('MARIA', '2005-7-10');

/*FUNCIONARIO*/
CREATE TABLE FUNCIONARIO (
    COD_FUNC SERIAL PRIMARY KEY, 
    NOME VARCHAR(100), 
    DT_NASC DATE
);
INSERT INTO FUNCIONARIO (NOME, DT_NASC)
VALUES ('RABICO', '1960-10-5');
INSERT INTO FUNCIONARIO (NOME, DT_NASC)
VALUES ('ADOLFO', '2000-3-20');
INSERT INTO FUNCIONARIO (NOME, DT_NASC)
VALUES ('JOAQUIM', '2000-5-29');
INSERT INTO FUNCIONARIO (NOME, DT_NASC)
VALUES ('CLEITON', '1980-3-20');

/*CONSULTA*/
SELECT C.NOME FROM CATEGORIA AS C 
JOIN APARTAMENTO AS A ON C.COD_CAT = A.COD_CAT
JOIN RESERVA AS R ON A.NUM_AP = R.NUM_AP
JOIN HOSPEDE AS H ON R.COD_HOSP = H.COD_HOSP
WHERE H.NOME ILIKE 'MARIA';

UNION

SELECT C.NOME FROM CATEGORIA AS C 
JOIN APARTAMENTO AS A ON C.COD_CAT = A.COD_CAT
JOIN HOSPEDAGEM AS HG ON A.NUM_AP = HG.NUM_AP
JOIN HOSPEDE AS H ON HG.COD_HOSP = H.COD_HOSP
JOIN FUNCIONARIO AS F ON HG.COD_FUNC = F.COD_FUNC
WHERE H.NOME ILIKE 'JOAO'
AND F.NOME ILIKE 'JOAQUIM';
