/*Crie uma tabela aluno com as colunas matrícula e nome.
Depois crie um trigger que não permita o cadastro de alunos
cujo nome começa com a letra “a”.*/

CREATE FUNCTION odioAoA() RETURNS TRIGGER AS
$$
    BEGIN 
    IF NEW.NOME ILIKE 'A%' THEN
        RAISE EXCEPTION 'NAO E PERMITIDO A MATRICULA DE ALUNOS COM NOMES COMECADOS COM A';
    END IF; 
    RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

CREATE TABLE ALUNOS
(MATRICULA SERIAL PRIMARY KEY, NOME VARCHAR(100));

CREATE TRIGGER ODIO_AO_A
BEFORE INSERT OR UPDATE ON ALUNOS
FOR EACH ROW 
EXECUTE PROCEDURE odioAoA();

INSERT INTO ALUNOS(NOME)
VALUES('JOAO');
INSERT INTO ALUNOS(NOME)
VALUES('MARIA');
INSERT INTO ALUNOS(NOME)
VALUES('ANA');