/*1. Nomes das categorias que possuam preços entre R$ 100,00 e R$ 200,00.*/

CREATE TABLE CATEGORIA 
(NOME VARCHAR(100), PRECO DECIMAL(10,2), DESCRICAO TEXT);
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('LUXO', 300.00, 'PARA RICOS');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('DUBLE', 200.00, 'PARA DUBLES');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('MEDIO', 150.00, 'CLASSE MEDIA');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('POBRE', 100.00, 'PARA POBRES');

SELECT NOME FROM CATEGORIA 
WHERE PRECO BETWEEN 100.00 AND 200.00;

