/*2. Nomes das categorias cujos nomes possuam a palavra ‘Luxo’.*/

CREATE TABLE CATEGORIA 
(NOME VARCHAR(100), PRECO DECIMAL(10,2), DESCRICAO TEXT);
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('LUXO', 300.00, 'PARA RICOS');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('DUBLE', 200.00, 'PARA DUBLES');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('MEDIO', 150.00, 'CLASSE MEDIA');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('POBRE', 100.00, 'PARA POBRES');

SELECT NOME FROM CATEGORIA 
WHERE NOME ILIKE '%LUXO%';