/*6. Quantidade de apartamentos cadastrados no sistema.*/

CREATE TABLE CATEGORIA 
(COD_CAT SERIAL PRIMARY KEY, NOME VARCHAR(100), PRECO INT, DESCRICAO TEXT);
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('LUXO', 300, 'PARA RICOS');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('DUBLE', 200, 'PARA DUBLES');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('MEDIO', 150, 'CLASSE MEDIA');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('POBRE', 100, 'PARA POBRES');

CREATE TABLE APARTAMENTO 
(NUM_AP SERIAL PRIMARY KEY, COD_CAT INT,
FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA(COD_CAT));
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (1);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (2);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (3);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (4);

CREATE TABLE HOSPEDAGEM 
(COD_HOSPEDAGEM SERIAL PRIMARY KEY, NUM_AP INT, DT_ENT DATE, DT_SAIDA DATE,
FOREIGN KEY (NUM_AP) REFERENCES APARTAMENTO(NUM_AP));
INSERT INTO HOSPEDAGEM (NUM_AP, DT_ENT, DT_SAIDA)
VALUES (1, '2025-1-1', '2025-1-2');
INSERT INTO HOSPEDAGEM (NUM_AP, DT_ENT, DT_SAIDA)
VALUES (2, '2025-1-1', '2025-1-3');
INSERT INTO HOSPEDAGEM (NUM_AP, DT_ENT, DT_SAIDA)
VALUES (3, '2025-1-1', '2025-1-4');
INSERT INTO HOSPEDAGEM (NUM_AP, DT_ENT, DT_SAIDA)
VALUES (4, '2025-1-1', NULL);

SELECT COUNT(*) FROM APARTAMENTO