/*17. Reajuste em 10% o valor das diárias das categorias*/

CREATE TABLE CATEGORIA 
(COD_CAT SERIAL PRIMARY KEY, NOME VARCHAR(100), PRECO INT, DESCRICAO TEXT);
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('LUXO', 300, 'PARA RICOS');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('DUBLE', 200, 'PARA DUBLES');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('MEDIO', 150, 'CLASSE MEDIA');
INSERT INTO CATEGORIA (NOME, PRECO, DESCRICAO) 
VALUES ('POBRE', 100, 'PARA POBRES');

CREATE TABLE APARTAMENTO 
(NUM_AP SERIAL PRIMARY KEY, COD_CAT INT,
FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA(COD_CAT));
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (1);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (2);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (3);
INSERT INTO APARTAMENTO (COD_CAT)
VALUES (4);

CREATE TABLE HOSPEDAGEM 
(COD_HOSPEDAGEM SERIAL PRIMARY KEY, NUM_AP INT, COD_HOSP INT, DT_ENT DATE, DT_SAIDA DATE,
FOREIGN KEY (NUM_AP) REFERENCES APARTAMENTO(NUM_AP),
FOREIGN KEY (COD_HOSP) REFERENCES HOSPEDE(COD_HOSP));
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, DT_ENT, DT_SAIDA)
VALUES (1, 1, '2025-1-1', '2025-1-2');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, DT_ENT, DT_SAIDA)
VALUES (2, 2, '2025-1-1', '2025-1-3');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, DT_ENT, DT_SAIDA)
VALUES (3, 3, '2025-1-1', '2025-1-4');
INSERT INTO HOSPEDAGEM (NUM_AP, COD_HOSP, DT_ENT, DT_SAIDA)
VALUES (4, 4, '2025-1-1', NULL);

CREATE TABLE HOSPEDE (COD_HOSP SERIAL PRIMARY KEY, NOME VARCHAR(100), DT_NASC DATE);
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('CHICO', '2005-1-6');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('SEU JOAO', '1967-3-20');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('DONA ANGELA', '1972-12-8');
INSERT INTO HOSPEDE (NOME, DT_NASC)
VALUES ('CHICA', '2005-7-10');

ALTER TABLE HOSPEDE 
ADD COLUMN NAC VARCHAR (100);

UPDATE HOSPEDE
SET NAC = 'ANGOLANO'
WHERE NOME = 'CHICO';

UPDATE HOSPEDE 
SET NAC = 'BRASILEIRO'
WHERE NOME = 'SEU JOAO';

UPDATE HOSPEDE 
SET NAC = 'URUGUAIA'
WHERE NOME = 'DONA ANGELA';

UPDATE HOSPEDE
SET NAC = 'MEXICANA'
WHERE NOME = 'CHICA';

UPDATE CATEGORIA 
SET PRECO = PRECO * 1.10;



