CREATE OR REPLACE FUNCTION finalizar_hospedagem(COD_HOSPEDAGEM_P INT) 
RETURNS TEXT
AS $$
DECLARE 
    hospedagem_exist INT;
BEGIN
    SELECT COUNT(*) INTO hospedagem_exist 
    FROM HOSPEDAGEM 
    WHERE COD_HOSPEDAGEM = COD_HOSPEDAGEM_P;

    IF hospedagem_exist = 0 THEN
        RETURN 'HOSPEDAGEM NÃO EXISTE';
    END IF;

    UPDATE HOSPEDAGEM
    SET DT_SAIDA = CURRENT_DATE
    WHERE COD_HOSPEDAGEM = COD_HOSPEDAGEM_P;

    RETURN 'HOSPEDAGEM FINALIZADA';
END;
$$ LANGUAGE plpgsql;

SELECT * FROM HOSPEDAGEM
SELECT finalizar_hospedagem(7);
SELECT finalizar_hospedagem(4);
SELECT * FROM HOSPEDAGEM;
SELECT finalizar_hospedagem(6);
SELECT * FROM HOSPEDAGEM;


