CREATE ROLE GERENTE;
CREATE ROLE ATENDENTE;
CREATE ROLE ESTAGIARIO;

GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO gerente WITH GRANT OPTION;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO gerente WITH GRANT OPTION;

GRANT EXECUTE ON ALL FUNCTION IN SCHEMA public TO ATENDENTE;

GRANT SELECT ON NOME_IDADE TO ESTAGIARIO;



