/*CRIE UM TRIGGER QUE, SEMPRE QUE HOUVER DECREMENTO DA QUANTIDADE EM ESTOQUE DE UM DETERMINADO PRODUTO, 
DECREMENTE TAMBÉM, CASO SEJA NECESSÁRIO, A QUANTIDADE EM ESTOQUE DO PRODUTOS QUE SÃO COMPOSTOS POR AQUELE QUE FOI DECREMENTADO.*/

CREATE FUNCTION controlador_estoque() RETURNS TRIGGER AS 
$$
DECLARE
    rec RECORD;
BEGIN
    UPDATE VENDA
    SET VALOR_TOTAL = ( 
        SELECT SUM(IV.QTD_VENDIDA * P.VALOR)
        FROM ITEM_VENDA AS IV
        JOIN PRODUTO AS P ON P.COD_PROD = IV.COD_PROD
        WHERE IV.COD_VENDA = NEW.COD_VENDA
    )
    WHERE COD_VENDA = NEW.COD_VENDA;
	
    IF NEW.COD_PROD = 4 OR NEW.COD_PROD = 5 THEN
        FOR rec IN
            SELECT COD_PROD_DO_COMBO, QTD_DE_PROD_NO_COMBO
            FROM COMBO
            WHERE COD_COMBO = NEW.COD_PROD
        LOOP
            UPDATE PRODUTO
            SET QTD_EM_ESTOQUE = QTD_EM_ESTOQUE - (rec.QTD_DE_PROD_NO_COMBO * NEW.QTD_VENDIDA)
            WHERE COD_PRODUTO = rec.COD_PROD_DO_COMBO;
        END LOOP;
    ELSE
        UPDATE PRODUTO 
        SET QTD_EM_ESTOQUE = QTD_EM_ESTOQUE - NEW.QTD_VENDIDA
        WHERE COD_PRODUTO = NEW.COD_PROD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER CONTROLADOR_ESTOQUE_TG
AFTER INSERT ON ITEM_VENDA
FOR EACH ROW EXECUTE FUNCTION controlador_estoque();
